# This is a basic workflow to help you get started with Actions

name: Lint check

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  # push:
  #  branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
          
      - name: Install Node.js dependencies in Crash_Course
        run: |
              cd Crash_Course
              npm ci
              
      - name: Install Node.js dependencies in Normal
        run: |
              cd Normal
              npm ci
          

      # Runs a single command using the runners shell
      - name: Lint check for Crash_Course
        run: |
              cd Crash_Course
              npm run lint
              
      - name: Lint check for Normal
        run: |
              cd Normal
              npm run lint              
      #- name: checking the test case coverage
      #  run: npm run test

      # Runs a set of commands using the runners shell
      #- name: Run a multi-line script
       # run: |
        #  echo Add other actions to build,
         # echo test, and deploy your project.
